# Jekyll configuration for GitHub Pages
# This enables clean URLs without .html extensions

# GitHub Pages uses Jekyll by default
# These settings will remove .html extensions from URLs

# Site settings
title: "Hernández Paint & Repair"
description: "Expert home repairs and painting. Clean work, clear pricing, fast scheduling."
url: "https://joelh11.github.io"
baseurl: "/hernandez-paint-repair"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Clean URLs configuration
plugins:
  - jekyll-sitemap

# Remove .html extensions
permalink: /:title/

# Exclude files that shouldn't be processed
exclude:
  - README.md
  - .gitignore

# Collections and defaults for clean URLs
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      permalink: /:basename/
